version: "3"
 
services:
  vue-cli:
    container_name: vue-sunportal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8081:8080"
    restart: always
